
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "code.cloudfoundry.org/bytefmt"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.2"

[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "3.0.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "5.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.0.0"

[[constraint]]
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/hellofresh/gcloud-opentracing"
  version = "1.0.1"

[[constraint]]
  name = "github.com/hellofresh/health-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hellofresh/logging-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/hellofresh/stats-go"
  version = "0.4.1"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tidwall/gjson"

[[constraint]]
  name = "github.com/ulule/limiter"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "sourcegraph.com/sourcegraph/appdash"
