################################################################
# Global configuration
################################################################

# port = 8080
#
# SSL certificate and key used
#
# Optional
#
# CertFile = "janus.crt"
# KeyFile = "janus.key"
#
# Enable debug mode
#
# Optional
# Default: false
#
# debug = true
#
# Log level
#
# Optional
# Default: "info"
#
# logLevel = "info"
#
# Timeout in seconds.
# Duration to give active requests a chance to finish during hot-reloads
#
# Optional
# Default: 10
#
# graceTimeOut = 10
# If non-zero, controls the maximum idle (keep-alive) to keep per-host.  If zero, DefaultMaxIdleConnsPerHost is used.
# If you encounter 'too many open files' errors, you can either change this value, or change `ulimit` value.
#
# Optional
# Default: http.DefaultMaxIdleConnsPerHost
#
# MaxIdleConnsPerHost = 200
#
# If set to true invalid SSL certificates are accepted for backends.
# Note: This disables detection of man-in-the-middle attacks so should only be used on secure backend networks.
# Optional
# Default: false
#
# InsecureSkipVerify = false
#
# Flush interval for upgraded Proxy connections.
# Optional
# BackendFlushInterval = 0
#
# Defines the time period of how often the idle connections maintained by the proxy are closed.
# Optional
# CloseIdleConnsPeriod = 0

################################################################
# Management API configuration backend
################################################################
[web]
# port = 8081

# SSL certificate and key used
#
# Optional
#
# CertFile = "janus.crt"
# KeyFile = "janus.key"
#
# Set REST API to read-only mode
#
# Optional
# ReadOnly = false
#
# Basic JWT configuration
#
# Required
#
  [credentials]
    secret = "secret key"
    username = "admin"
    password = "admin"

################################################################
# Metrics
################################################################
# To enable Janus to export internal metrics to Statsd
#[stats]
#    dsn = "statsd:8125"
#    prefix = "sandbox.janus."

################################################################
# Storage
################################################################
# You can choose to use `redis` or `in memory` datastores
# [storage]
#   dsn = "memory://localhost"
#
# If you wanna use redis enable this
# [storage]
#   dsn = "redis://janus-storage:6379"

################################################################
# Proxy Definition Database
################################################################
# You can choose to use `mongodb` or `file based` databases to store your
# API definition configuration.
#
# WARNING, if you use Janus in Docker, you have 2 options:
#  - create a file on your host and mount it as a volume
#      storageFile = "acme.json"
#      $ docker run -v "/my/host/janus" janus
#  - mount the folder containing the file as a volume
#      dsn = "file:///etc/janus"
#      $ docker run -v "/my/host/acme:/etc/janus" janus
#
# Required
#
# [database]
#   dsn = "file:///etc/janus"
#
# If you want to use mongodb enable this
# [database]
#   dsn = "mongodb://janus-database:27017/janus"


################################################################
# Distributed Tracing
################################################################
#
# [tracing]

# Google Clooud Platform - Stackdriver Trace
  # [googleCloud]
  #   projectID = ""
  #   email = ""
  #   privateKey = ""
  #   privateKeyID = ""

# Appdash - Embedded Server
  # [appdash]
  #   dsn = "localhost:8701"
  #   url = ":8700"

# Appdash - Remote Server
  # [appdash]
  #   dsn = "remote-url:8701"
