----
 platform: linux
 
 image_resource:
   type: docker-image
   source:
     repository: golang
     tag: "1"
 
 inputs:
   - name: source-code
   - name: release-candidate
 
 outputs:
   - name: docker-images
 
 run:
   path: source-code/ci/scripts/docker-deployment.sh
