apiVersion: v1
kind: Service
metadata:
  name: {{ include "janus.fullname" ( dict "name" .Values.service.name ) }}
  labels:
{{ include "janus.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "janus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
